version: "3.9"
services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-doh
    restart: unless-stopped
    command: proxy-dns --address 0.0.0.0 --port 5053
    expose:
      - "5053"
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /var/tmp

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    depends_on:
      - cloudflared
    restart: unless-stopped
    ports:
      - "192.168.0.29:53:53/tcp"
      - "192.168.0.29:53:53/udp"
      - "192.168.0.29:8081:80/tcp"
    environment:
      TZ: "America/Detroit"
      WEB_PORT: "80"
      FTLCONF_dns_listeningMode: "ALL"
      FTLCONF_dns_upstreams: "cloudflared#5053"
    volumes:
      - ./config/pihole:/etc/pihole
      - ./config/dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    security_opt:
      - no-new-privileges:true
